### ISSUE TITLE
Error with Groovy console method and OSM : Conflicting module version

### ISSUE THREAD

**Issue by franetibe** [orbisgis/geoclimate#575]
I run Geoclimate using the Groovy console and the following script :

```
@GrabResolver(name='orbisgis', root='https://nexus.orbisgis.org/repository/orbisgis/')
@Grab(group='org.orbisgis.orbisprocess', module='geoclimate', version='1.0.0-SNAPSHOT')

import org.orbisgis.orbisprocess.geoclimate.Geoclimate

def process = Geoclimate.OSM.workflow
process.execute(configurationFile:'/home/.../Geoclimate/my_first_config_file_osm.json')
```

The configuration file is the following : 

```json
{
    "description": "Processing OSM data",
    "geoclimatedb": {
        "folder": "/tmp/osm",
        "name": "geoclimate_db_test;AUTO_SERVER=TRUE",
        "delete": true
    },
    "input": {
        "osm": [
            "Pont-de-Veyle"
        ]
    },
    "output": {
        "folder": "/tmp"
    },
    "parameters": {
        "rsu_indicators": {
            "indicatorUse": [
                "LCZ",
                "TEB",
                "URBAN_TYPOLOGY"
            ],
            "svfSimplified": true,
            "estimateHeight": true
        }
    }
}
```

Geoclimate returns the following message :

```
1 compilation error:

Exception thrown

groovy.lang.GroovyRuntimeException: Conflicting module versions. Module [groovy-sql is loaded in version 3.0.8 and you are trying to load version 3.0.7
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

The command `groovy -v` returns `Groovy Version: 3.0.8 JVM: 11.0.11 Vendor: Ubuntu OS: Linux`

Why am I trying to load groovy version 3.0.7 ?

**Comment by j3r3m1** [comment]
I think that the exception returned is quite unclear. It says that you need to load groovy 3.0.7 for using Geoclimate while you are loading 3.0.8.

**Comment by ebocher** [comment]
It' s because Groovy  3.0.8 is installed on your machine as default. You must use 3.0.7

**Comment by franetibe** [comment]
It is working with Groovy 3.0.7, I will underline this in the tutorial. I close the issue.
